# Generated by Django 4.1.5 on 2023-01-13 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='hora',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clinica.horarios'),
            preserve_default=False,
        ),
    ]
