# Generated by Django 4.1.5 on 2023-01-17 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('sexo', models.CharField(choices=[('1', 'Prefiro não dizer'), ('2', 'Masculino'), ('3', 'Feminino')], max_length=20)),
                ('telefone', models.CharField(max_length=11)),
            ],
        ),
        migrations.AlterField(
            model_name='medico',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.agenda')),
            ],
        ),
    ]
