# Generated by Django 4.1.5 on 2023-01-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_horarios_agenda_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='hora',
        ),
        migrations.AddField(
            model_name='agenda',
            name='hora',
            field=models.ManyToManyField(blank=True, to='clinica.horarios'),
        ),
    ]
