# Generated by Django 4.1.5 on 2023-01-17 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_cliente_alter_medico_email_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='cliente',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='clinica.cliente'),
            preserve_default=False,
        ),
    ]
