# Generated by Django 4.1.5 on 2023-01-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_remove_agenda_hora_agenda_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='hora',
        ),
        migrations.DeleteModel(
            name='horarios',
        ),
    ]
