# Generated by Django 4.1.5 on 2023-01-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_consulta_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='hora',
        ),
    ]
