# Generated by Django 4.1.5 on 2023-01-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_remove_agenda_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='hora',
            field=models.CharField(choices=[('1', '07:00 ás 08:00'), ('2', '08:00 ás 09:00'), ('3', '09:00 ás 10:00'), ('4', '10:00 ás 11:00'), ('5', '11:00 ás 12:00')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
