# Generated by Django 4.1.5 on 2023-01-14 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_agenda_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='horario',
            new_name='hora',
        ),
    ]
